export const assessmentRounds = [
  {
    id: "ROUND-2569-06",
    label: "ปี 2569 เดือน 6",
    detail: "รอบกลางปี 2569",
    year: "2569",
    startDate: "1 มิ.ย. 2569",
    endDate: "30 มิ.ย. 2569",
    status: "open",
    statusText: "เปิดใช้งาน",
    statusColor: "processing",
    assessmentType: "supervisor",
    formId: "FORM-SUP-DEFAULT",
  },
  {
    id: "ROUND-2569-12",
    label: "ปี 2569 เดือน 12",
    detail: "รอบปลายปี 2569",
    year: "2569",
    startDate: "1 ธ.ค. 2569",
    endDate: "31 ธ.ค. 2569",
    status: "draft",
    statusText: "ร่าง",
    statusColor: "default",
    assessmentType: "supervisor",
    formId: "FORM-SUP-DEFAULT",
  },
  {
    id: "ROUND-2568",
    label: "ปี 2568",
    detail: "รอบประจำปี 2568",
    year: "2568",
    startDate: "1 ธ.ค. 2568",
    endDate: "31 ธ.ค. 2568",
    status: "approved",
    statusText: "อนุมัติผลแล้ว",
    statusColor: "blue",
    assessmentType: "supervisor",
    formId: "FORM-SUP-ANNUAL",
  },
];

export const assessmentForms = [
  {
    id: "FORM-SUP-DEFAULT",
    name: "แบบประเมินผู้บังคับบัญชามาตรฐาน",
    description: "ใช้ประเมินภาวะผู้นำ การสื่อสาร การบริหารทีม และจริยธรรม",
    topicCount: 3,
    questionCount: 10,
    status: "พร้อมใช้งาน",
    isSelectable: true,
    assessmentType: "supervisor",
    topics: [
      {
        title: "ภาวะผู้นำและการตัดสินใจ",
        questions: [
          "สื่อสารเป้าหมายและแนวทางการทำงานให้ทีมเข้าใจชัดเจน",
          "ตัดสินใจบนข้อมูลและรับผิดชอบต่อผลลัพธ์",
          "สนับสนุนทีมเมื่อต้องแก้ปัญหาเร่งด่วน",
        ],
      },
      {
        title: "การบริหารคนและการพัฒนาทีม",
        questions: [
          "ให้คำแนะนำหรือ feedback ที่นำไปปรับปรุงงานได้จริง",
          "มอบหมายงานเหมาะสมกับความสามารถของแต่ละคน",
          "ส่งเสริมบรรยากาศการทำงานที่เปิดใจและร่วมมือกัน",
        ],
      },
      {
        title: "ความรับผิดชอบและจริยธรรมในการทำงาน",
        questions: [
          "ปฏิบัติต่อทีมอย่างยุติธรรมและให้เกียรติ",
          "รักษามาตรฐานงานและกฎระเบียบขององค์กร",
          "เป็นแบบอย่างด้านความรับผิดชอบและวินัยในการทำงาน",
          "บริหารความขัดแย้งในทีมอย่างเหมาะสม",
        ],
      },
    ],
  },
  {
    id: "FORM-SUP-ANNUAL",
    name: "แบบประเมินหัวหน้าประจำปี",
    description: "เพิ่มหัวข้อผลการปฏิบัติงานประจำปีและแผนพัฒนา",
    topicCount: 4,
    questionCount: 14,
    status: "พร้อมใช้งาน",
    isSelectable: true,
    assessmentType: "supervisor",
    topics: [
      {
        title: "ภาวะผู้นำ",
        questions: ["สื่อสารทิศทางทีมได้ชัดเจน", "ติดตามงานและตัดสินใจได้เหมาะสม"],
      },
      {
        title: "การบริหารทีม",
        questions: ["พัฒนาศักยภาพทีมอย่างต่อเนื่อง", "กระจายงานอย่างเหมาะสม"],
      },
      {
        title: "ผลการปฏิบัติงาน",
        questions: ["ผลักดันเป้าหมายของหน่วยงานได้สำเร็จ", "รักษาคุณภาพงานตามมาตรฐาน"],
      },
      {
        title: "แผนพัฒนา",
        questions: ["เปิดรับข้อเสนอแนะ", "มีแนวทางพัฒนาทีมในรอบถัดไป"],
      },
    ],
  },
  {
    id: "FORM-SUP-TRIAL",
    name: "แบบประเมินทดลองใช้",
    description: "ประเมินพฤติกรรมผู้บังคับบัญชาแบบ 5 ระดับ พร้อมจุดเด่น ด้านที่ควรพัฒนา และข้อเสนอแนะ",
    topicCount: 5,
    questionCount: 25,
    status: "ร่าง",
    isSelectable: false,
    assessmentType: "supervisor",
    topics: [
      {
        title: "ภาวะผู้นำ (Leadership)",
        type: "rating",
        scoreMin: 1,
        scoreMax: 5,
        questions: [
          "มีภาวะผู้นำและความน่าเชื่อถือ",
          "กล้าตัดสินใจและรับผิดชอบ",
          "วางแผนและบริหารงานอย่างเป็นระบบ",
          "ติดตามงานและเป้าหมายอย่างต่อเนื่อง",
          "เป็นแบบอย่างที่ดีในการทำงาน",
        ],
      },
      {
        title: "การสื่อสาร (Communication)",
        type: "rating",
        scoreMin: 1,
        scoreMax: 5,
        questions: [
          "สื่อสารชัดเจน เข้าใจง่าย",
          "รับฟังความคิดเห็นของทีม",
          "ถ่ายทอดนโยบายและเป้าหมายได้ชัดเจน",
          "ใช้ถ้อยคำเหมาะสมในการสื่อสาร",
          "ประสานงานได้รวดเร็วและทั่วถึง",
        ],
      },
      {
        title: "การบริหารทีม (People Management)",
        type: "rating",
        scoreMin: 1,
        scoreMax: 5,
        questions: [
          "ปฏิบัติต่อพนักงานอย่างเท่าเทียม",
          "สนับสนุนและช่วยเหลือทีมงาน",
          "สร้างแรงจูงใจและขวัญกำลังใจ",
          "เปิดโอกาสให้ทีมมีส่วนร่วม",
          "ส่งเสริมการทำงานเป็นทีม",
        ],
      },
      {
        title: "การบริหารงาน (Execution & Performance)",
        type: "rating",
        scoreMin: 1,
        scoreMax: 5,
        questions: [
          "แก้ไขปัญหาได้ตรงจุด",
          "ตัดสินใจได้รวดเร็ว",
          "สนับสนุนการทำงานภาคสนาม",
          "ติดตามงานอย่างใกล้ชิด",
          "บริหารงานได้ตามเป้าหมาย",
        ],
      },
      {
        title: "จริยธรรมและความเป็นมืออาชีพ (Professionalism)",
        type: "rating",
        scoreMin: 1,
        scoreMax: 5,
        questions: [
          "มีความโปร่งใสในการทำงาน",
          "ใช้เหตุผลและความเป็นธรรม",
          "ควบคุมอารมณ์ได้เหมาะสม",
          "วางตัวเหมาะสมกับตำแหน่ง",
          "ปฏิบัติตามกฎระเบียบองค์กร",
        ],
      },
      {
        title: "ส่วนที่ 2 : จุดเด่นของผู้บังคับบัญชา",
        type: "checkbox",
        maxSelections: 3,
        questions: [
          "รับฟังความคิดเห็น",
          "ให้คำปรึกษาได้ดี",
          "เป็นธรรมและโปร่งใส",
          "ตัดสินใจรวดเร็ว",
          "แก้ปัญหาได้ดี",
          "สนับสนุนทีมงาน",
          "ทำงานเป็นระบบ",
          "สร้างแรงจูงใจได้ดี",
          "อื่นๆ",
        ],
      },
    ],
  },
];

export const supervisorRows = [
  {
    id: "ADM-SV001",
    roundId: "ROUND-2569-06",
    employeeCode: "SL00123",
    name: "คุณณัฐพล วัฒนากุล",
    position: "หัวหน้าฝ่ายขาย",
    department: "ฝ่ายขาย",
    workArea: "สำนักงานใหญ่",
    round: "ไตรมาส 2/2569",
    totalEvaluators: 18,
    submitted: 15,
    pending: 3,
    averageScore: 3.72,
    status: "กำลังประเมิน",
    statusColor: "processing",
    hrApproved: false,
  },
  {
    id: "ADM-SV002",
    roundId: "ROUND-2569-06",
    employeeCode: "SL00124",
    name: "คุณพิชชาภา แสงอรุณ",
    position: "ผู้ช่วยหัวหน้าฝ่ายขาย",
    department: "ฝ่ายขาย",
    workArea: "สำนักงานใหญ่",
    round: "ไตรมาส 2/2569",
    totalEvaluators: 12,
    submitted: 12,
    pending: 0,
    averageScore: 3.58,
    status: "ประเมินครบแล้ว",
    statusColor: "success",
    hrApproved: true,
  },
  {
    id: "ADM-SV003",
    roundId: "ROUND-2569-06",
    employeeCode: "SL00125",
    name: "คุณศุภชัย เมธากุล",
    position: "หัวหน้าฝ่ายบริการลูกค้า",
    department: "ฝ่ายบริการลูกค้า",
    workArea: "สาขารังสิต",
    round: "ไตรมาส 2/2569",
    totalEvaluators: 22,
    submitted: 14,
    pending: 8,
    averageScore: 3.31,
    status: "รอติดตาม",
    statusColor: "warning",
    hrApproved: false,
  },
  {
    id: "ADM-SV004",
    roundId: "ROUND-2569-06",
    employeeCode: "SL00126",
    name: "คุณมณีรัตน์ ธนากร",
    position: "หัวหน้าฝ่ายคลังสินค้า",
    department: "ฝ่ายคลังสินค้า",
    workArea: "สาขาบางนา",
    round: "ไตรมาส 2/2569",
    totalEvaluators: 16,
    submitted: 16,
    pending: 0,
    averageScore: 3.84,
    status: "อนุมัติรับทราบแล้ว",
    statusColor: "blue",
    hrApproved: true,
  },
  {
    id: "ADM-SV005",
    roundId: "ROUND-2569-12",
    employeeCode: "SL00127",
    name: "คุณธนวัฒน์ ศรีสุข",
    position: "หัวหน้าฝ่ายปฏิบัติการ",
    department: "ฝ่ายปฏิบัติการ",
    workArea: "สาขาเชียงใหม่",
    round: "ปี 2569 เดือน 12",
    totalEvaluators: 20,
    submitted: 6,
    pending: 14,
    averageScore: 3.44,
    status: "กำลังประเมิน",
    statusColor: "processing",
    hrApproved: false,
  },
  {
    id: "ADM-SV006",
    roundId: "ROUND-2569-12",
    employeeCode: "SL00128",
    name: "คุณอรอนงค์ จันทร์ดี",
    position: "หัวหน้าฝ่ายสินเชื่อ",
    department: "ฝ่ายสินเชื่อ",
    workArea: "สำนักงานใหญ่",
    round: "ปี 2569 เดือน 12",
    totalEvaluators: 15,
    submitted: 15,
    pending: 0,
    averageScore: 3.91,
    status: "ประเมินครบแล้ว",
    statusColor: "success",
    hrApproved: false,
  },
  {
    id: "ADM-SV007",
    roundId: "ROUND-2568",
    employeeCode: "SL00129",
    name: "คุณนรินทร์ ทองแท้",
    position: "หัวหน้าฝ่ายทรัพยากรบุคคล",
    department: "ฝ่ายทรัพยากรบุคคล",
    workArea: "สำนักงานใหญ่",
    round: "ปี 2568",
    totalEvaluators: 18,
    submitted: 18,
    pending: 0,
    averageScore: 3.77,
    status: "อนุมัติรับทราบแล้ว",
    statusColor: "blue",
    hrApproved: true,
  },
  {
    id: "ADM-SV008",
    roundId: "ROUND-2568",
    employeeCode: "SL00130",
    name: "คุณลลิตา แก้วมณี",
    position: "หัวหน้าฝ่ายบัญชี",
    department: "ฝ่ายบัญชี",
    workArea: "สำนักงานใหญ่",
    round: "ปี 2568",
    totalEvaluators: 10,
    submitted: 10,
    pending: 0,
    averageScore: 3.63,
    status: "อนุมัติรับทราบแล้ว",
    statusColor: "blue",
    hrApproved: true,
  },
];

export const supervisorProfiles = [
  {
    employeeCode: "SL00123",
    name: "คุณณัฐพล วัฒนากุล",
    currentPosition: "หัวหน้าฝ่ายขาย",
    currentDepartment: "ฝ่ายขาย",
    currentWorkArea: "สำนักงานใหญ่",
    startWorkDate: "1 ก.พ. 2560",
    leaderStartDate: "1 ม.ค. 2565",
    status: "ปฏิบัติงาน",
    statusColor: "success",
    history: [
      {
        year: "2569",
        round: "ปี 2569 เดือน 6",
        position: "หัวหน้าฝ่ายขาย",
        department: "ฝ่ายขาย",
        workArea: "สำนักงานใหญ่",
        score: 3.72,
        totalEvaluators: 18,
        submitted: 15,
        resultStatus: "กำลังประเมิน",
      },
      {
        year: "2568",
        round: "ปี 2568",
        position: "ผู้ช่วยหัวหน้าฝ่ายขาย",
        department: "ฝ่ายขาย",
        workArea: "สำนักงานใหญ่",
        score: 3.58,
        totalEvaluators: 14,
        submitted: 14,
        resultStatus: "อนุมัติรับทราบแล้ว",
      },
    ],
    positionTimeline: [
      { date: "1 ม.ค. 2565", label: "ปรับตำแหน่งเป็นหัวหน้าฝ่ายขาย", workArea: "สำนักงานใหญ่" },
      { date: "1 เม.ย. 2563", label: "ย้ายเข้าสังกัดฝ่ายขาย", workArea: "สำนักงานใหญ่" },
      { date: "1 ก.พ. 2560", label: "เริ่มงานตำแหน่งเจ้าหน้าที่ขาย", workArea: "สาขารังสิต" },
    ],
  },
  {
    employeeCode: "SL00125",
    name: "คุณศุภชัย เมธากุล",
    currentPosition: "หัวหน้าฝ่ายบริการลูกค้า",
    currentDepartment: "ฝ่ายบริการลูกค้า",
    currentWorkArea: "สาขารังสิต",
    startWorkDate: "15 มี.ค. 2559",
    leaderStartDate: "1 มิ.ย. 2564",
    status: "ปฏิบัติงาน",
    statusColor: "success",
    history: [
      {
        year: "2569",
        round: "ปี 2569 เดือน 6",
        position: "หัวหน้าฝ่ายบริการลูกค้า",
        department: "ฝ่ายบริการลูกค้า",
        workArea: "สาขารังสิต",
        score: 3.31,
        totalEvaluators: 22,
        submitted: 14,
        resultStatus: "รอติดตาม",
      },
      {
        year: "2568",
        round: "ปี 2568",
        position: "หัวหน้าฝ่ายบริการลูกค้า",
        department: "ฝ่ายบริการลูกค้า",
        workArea: "สาขาอยุธยา",
        score: 3.67,
        totalEvaluators: 18,
        submitted: 18,
        resultStatus: "อนุมัติรับทราบแล้ว",
      },
    ],
    positionTimeline: [
      { date: "1 ม.ค. 2569", label: "ย้ายพื้นที่ดูแลเป็นสาขารังสิต", workArea: "สาขารังสิต" },
      { date: "1 มิ.ย. 2564", label: "ปรับตำแหน่งเป็นหัวหน้าฝ่ายบริการลูกค้า", workArea: "สาขาอยุธยา" },
      { date: "15 มี.ค. 2559", label: "เริ่มงานตำแหน่งเจ้าหน้าที่บริการลูกค้า", workArea: "สำนักงานใหญ่" },
    ],
  },
  {
    employeeCode: "SL00129",
    name: "คุณนรินทร์ ทองแท้",
    currentPosition: "หัวหน้าฝ่ายทรัพยากรบุคคล",
    currentDepartment: "ฝ่ายทรัพยากรบุคคล",
    currentWorkArea: "สำนักงานใหญ่",
    startWorkDate: "1 ก.ค. 2558",
    leaderStartDate: "1 ม.ค. 2563",
    status: "ปฏิบัติงาน",
    statusColor: "success",
    history: [
      {
        year: "2568",
        round: "ปี 2568",
        position: "หัวหน้าฝ่ายทรัพยากรบุคคล",
        department: "ฝ่ายทรัพยากรบุคคล",
        workArea: "สำนักงานใหญ่",
        score: 3.77,
        totalEvaluators: 18,
        submitted: 18,
        resultStatus: "อนุมัติรับทราบแล้ว",
      },
    ],
    positionTimeline: [
      { date: "1 ม.ค. 2563", label: "ปรับตำแหน่งเป็นหัวหน้าฝ่ายทรัพยากรบุคคล", workArea: "สำนักงานใหญ่" },
      { date: "1 ก.ค. 2558", label: "เริ่มงานตำแหน่งเจ้าหน้าที่ HR", workArea: "สำนักงานใหญ่" },
    ],
  },
];

export const supervisorDetailSections = [
  {
    title: "ส่วนที่ 1 : การประเมินโดยผู้ใต้บังคับบัญชา",
    accent: "teal",
    totalTitle: "คะแนนประเมินโดยรวมจากผู้ใต้บังคับบัญชา",
    score: 4.2,
    label: "ดีเยี่ยม",
    icon: "leadership",
    metrics: [
      { label: "ภาวะผู้นำ", score: 4.5, trend: "up" },
      { label: "การสื่อสาร", score: 3.8, trend: "up" },
      { label: "การบริหารทีม", score: 4.2, trend: "up" },
      { label: "จริยธรรมและความเป็นมืออาชีพ", score: 4.5, trend: "up" },
    ],
    comments: [
      "มีภาวะผู้นำที่ดี สามารถสื่อสารและประสานงานกับทีมได้อย่างมีประสิทธิภาพ",
      "เป็นผู้นำที่เข้มแข็ง ควรพัฒนาการสื่อสารภายในทีมให้ชัดเจนมากยิ่งขึ้น",
      "ควรปรับปรุงแนวทางการสื่อสารและสร้างความร่วมมือในทีมให้ดียิ่งขึ้น",
    ],
  },
  {
    title: "ส่วนที่ 2 : การทำงานร่วมกันและความเป็นหนึ่งเดียวของทีม",
    accent: "blue",
    totalTitle: "คะแนนการทำงานร่วมกันโดยรวม",
    score: 4.6,
    label: "ดีเด่น",
    icon: "team",
    metrics: [
      { label: "ความรับผิดชอบ", score: 4.8, trend: "up" },
      { label: "การทำงานเป็นทีม", score: 4.6, trend: "up" },
      { label: "ทักษะด้านมนุษยสัมพันธ์", score: 4.4, trend: "up" },
    ],
    comments: [
      "ช่วยส่งเสริมการทำงานร่วมกันและการประสานงานในทีมได้ดี",
      "ช่วยให้เกิดการทำงานร่วมกันระหว่างสมาชิกในทีม และช่วยลดปัญหาด้านการสื่อสาร",
      "ช่วยให้สามารถนำความคิดเห็นของเพื่อนร่วมงานมาปรับปรุงวิธีการทำงานร่วมกันได้ดีขึ้น",
    ],
  },
  {
    title: "ส่วนที่ 3 : การประเมินผลการปฏิบัติงานประจำปี",
    accent: "navy",
    totalTitle: "คะแนนผลการปฏิบัติงานโดยรวม",
    score: 4.3,
    label: "ดีเยี่ยม",
    icon: "target",
    metrics: [
      { label: "การบรรลุเป้าหมาย", score: 4.4, trend: "up" },
      { label: "คุณภาพของงาน", score: 4.3, trend: "up" },
      { label: "ความคิดริเริ่ม", score: 4.2, trend: "up" },
      { label: "การปรับตัว", score: 4.4, trend: "up" },
      { label: "การมุ่งเน้นลูกค้า", score: 4.3, trend: "up" },
    ],
    summary: [
      "บรรลุเป้าหมายประจำปี 105% ในโครงการด้าน HR",
      "ปรับปรุงกระบวนการสรรหา ทำให้ระยะเวลาในการสรรหาลดลง 20%",
      "พัฒนาโปรแกรมฝึกอบรมที่ได้รับการนำไปใช้ในระดับองค์กร",
    ],
    developmentPlan: [
      "พัฒนาทักษะด้านการวิเคราะห์ข้อมูล",
      "พัฒนาความสามารถด้านการวางแผน HR เชิงกลยุทธ์",
      "เข้าร่วมโปรแกรมพัฒนาภาวะผู้นำ",
    ],
  },
];

export const assessmentApprovalItems = [
  {
    id: "APR-2569-001",
    round: "ไตรมาส 2/2569",
    evaluatorName: "คุณวิชาญ รัตนกุล",
    evaluatorCode: "EMP01021",
    evaluatorDepartment: "ฝ่ายขาย",
    supervisorName: "คุณณัฐพล วัฒนากุล",
    supervisorPosition: "หัวหน้าฝ่ายขาย",
    submittedAt: "30 มิ.ย. 2569 14:22",
    status: "รอตรวจ",
    statusColor: "warning",
    editedComment: "",
    originalComment:
      "หัวหน้าช่วยวางแผนงานดี แต่บางครั้งสื่อสารเร็วและกดดันทีมมากเกินไป ควรปรับน้ำเสียงและเวลาแจ้งงานให้เหมาะสมขึ้น",
    answers: [
      {
        topic: "ภาวะผู้นำและการตัดสินใจ",
        children: [
          { title: "สื่อสารเป้าหมายและแนวทางการทำงานให้ทีมเข้าใจชัดเจน", score: 3 },
          { title: "ตัดสินใจบนข้อมูลและรับผิดชอบต่อผลลัพธ์", score: 4 },
          { title: "สนับสนุนทีมเมื่อต้องแก้ปัญหาเร่งด่วน", score: 4 },
        ],
      },
      {
        topic: "การบริหารคนและการพัฒนาทีม",
        children: [
          { title: "ให้คำแนะนำหรือ feedback ที่นำไปปรับปรุงงานได้จริง", score: 3 },
          { title: "มอบหมายงานเหมาะสมกับความสามารถของแต่ละคน", score: 4 },
          { title: "ส่งเสริมบรรยากาศการทำงานที่เปิดใจและร่วมมือกัน", score: 3 },
        ],
      },
      {
        topic: "ความรับผิดชอบและจริยธรรมในการทำงาน",
        children: [
          { title: "ปฏิบัติต่อทีมอย่างยุติธรรมและให้เกียรติ", score: 4 },
          { title: "รักษามาตรฐานงานและกฎระเบียบขององค์กร", score: 4 },
          { title: "เป็นแบบอย่างด้านความรับผิดชอบและวินัยในการทำงาน", score: 3 },
          { title: "บริหารความขัดแย้งในทีมอย่างเหมาะสม", score: 3 },
        ],
      },
    ],
  },
  {
    id: "APR-2569-002",
    round: "ไตรมาส 2/2569",
    evaluatorName: "คุณปาลิตา นวลจันทร์",
    evaluatorCode: "EMP01045",
    evaluatorDepartment: "ฝ่ายขาย",
    supervisorName: "คุณพิชชาภา แสงอรุณ",
    supervisorPosition: "ผู้ช่วยหัวหน้าฝ่ายขาย",
    submittedAt: "29 มิ.ย. 2569 10:08",
    status: "แก้ไขคอมเมนต์แล้ว",
    statusColor: "processing",
    originalComment:
      "ช่วยประสานงานได้เร็ว แต่ควรลดคำพูดที่ทำให้ทีมรู้สึกไม่มั่นใจเวลางานเร่ง",
    editedComment:
      "ช่วยประสานงานได้รวดเร็ว ควรเพิ่มรูปแบบการสื่อสารที่สร้างความมั่นใจให้ทีมในช่วงงานเร่ง",
    answers: [
      {
        topic: "ภาวะผู้นำและการตัดสินใจ",
        children: [
          { title: "สื่อสารเป้าหมายและแนวทางการทำงานให้ทีมเข้าใจชัดเจน", score: 4 },
          { title: "ตัดสินใจบนข้อมูลและรับผิดชอบต่อผลลัพธ์", score: 3 },
          { title: "สนับสนุนทีมเมื่อต้องแก้ปัญหาเร่งด่วน", score: 4 },
        ],
      },
      {
        topic: "การบริหารคนและการพัฒนาทีม",
        children: [
          { title: "ให้คำแนะนำหรือ feedback ที่นำไปปรับปรุงงานได้จริง", score: 4 },
          { title: "มอบหมายงานเหมาะสมกับความสามารถของแต่ละคน", score: 3 },
          { title: "ส่งเสริมบรรยากาศการทำงานที่เปิดใจและร่วมมือกัน", score: 4 },
        ],
      },
    ],
  },
  {
    id: "APR-2569-003",
    round: "ไตรมาส 2/2569",
    evaluatorName: "คุณกิตติศักดิ์ ภักดี",
    evaluatorCode: "EMP01102",
    evaluatorDepartment: "ฝ่ายบริการลูกค้า",
    supervisorName: "คุณศุภชัย เมธากุล",
    supervisorPosition: "หัวหน้าฝ่ายบริการลูกค้า",
    submittedAt: "28 มิ.ย. 2569 16:40",
    status: "อนุมัติแล้ว",
    statusColor: "success",
    originalComment:
      "หัวหน้าช่วยแก้ปัญหาหน้างานได้ดี และให้คำแนะนำกับทีมอย่างต่อเนื่อง",
    editedComment: "",
    answers: [
      {
        topic: "ภาวะผู้นำและการตัดสินใจ",
        children: [
          { title: "สื่อสารเป้าหมายและแนวทางการทำงานให้ทีมเข้าใจชัดเจน", score: 4 },
          { title: "ตัดสินใจบนข้อมูลและรับผิดชอบต่อผลลัพธ์", score: 4 },
          { title: "สนับสนุนทีมเมื่อต้องแก้ปัญหาเร่งด่วน", score: 4 },
        ],
      },
      {
        topic: "ความรับผิดชอบและจริยธรรมในการทำงาน",
        children: [
          { title: "ปฏิบัติต่อทีมอย่างยุติธรรมและให้เกียรติ", score: 4 },
          { title: "รักษามาตรฐานงานและกฎระเบียบขององค์กร", score: 4 },
          { title: "เป็นแบบอย่างด้านความรับผิดชอบและวินัยในการทำงาน", score: 3 },
        ],
      },
    ],
  },
];

export function getPercent(submitted, total) {
  return Math.round((submitted / total) * 100);
}
